"""mod tables

Revision ID: c67cf22e34cd
Revises: 2fcca06c89ba
Create Date: 2023-06-07 16:35:43.376947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67cf22e34cd'
down_revision = '2fcca06c89ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_name', table_name='books')
    op.drop_table('books')
    op.drop_index('ix_search_results_name', table_name='search_results')
    op.drop_table('search_results')
    op.drop_index('ix_catalogues_name', table_name='catalogues')
    op.drop_table('catalogues')
    op.drop_table('items')
    op.drop_index('ix_messages_body', table_name='messages')
    op.drop_index('ix_messages_timestamp', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_topics_name', table_name='topics')
    op.drop_table('topics')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_table('grades')
    op.drop_index('ix_categories_name', table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_comments_timestamp', table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_timestamp', 'comments', ['timestamp'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('grade', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('avatar', sa.BLOB(), nullable=True),
    sa.Column('city', sa.VARCHAR(length=64), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=4), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('about_me', sa.TEXT(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('confirmed', sa.BOOLEAN(), nullable=True),
    sa.Column('role', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_topics_name', 'topics', ['name'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('discussion_topic_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_timestamp', 'messages', ['timestamp'], unique=False)
    op.create_index('ix_messages_body', 'messages', ['body'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('read_state', sa.VARCHAR(length=64), nullable=True),
    sa.Column('cataloge_id', sa.INTEGER(), nullable=True),
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['cataloge_id'], ['catalogues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogues',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_catalogues_name', 'catalogues', ['name'], unique=False)
    op.create_table('search_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cover', sa.BLOB(), nullable=True),
    sa.Column('isbn', sa.VARCHAR(length=64), nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('author', sa.VARCHAR(length=64), nullable=True),
    sa.Column('publishing_house', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('release_date', sa.DATE(), nullable=True),
    sa.Column('count_of_chapters', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_results_name', 'search_results', ['name'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cover', sa.BLOB(), nullable=True),
    sa.Column('isbn', sa.VARCHAR(length=64), nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('author', sa.VARCHAR(length=64), nullable=True),
    sa.Column('publishing_house', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('release_date', sa.DATE(), nullable=True),
    sa.Column('count_of_chapters', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_books_name', 'books', ['name'], unique=False)
    # ### end Alembic commands ###
